apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer # only work for cloud K8 clusters
  selector:
    app: nginx
    project: roboshop
    component: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80 # this port belongs to service
    targetPort: http-web-svc # This port belongs to container
