apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
    project: roboshop
    component: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: {{ .Values.service.port }} #this port belongs to service
    targetPort: 80 #This port belongs to container
